server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "http://100.108.175.65:5173"
              - "http://100.123.65.55:5173"
              - "http://100.78.223.71:5173"
              - "chrome-extension://imgpenhngnbnmhdkpdfnfhdpmfgmihdn"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedHeaders: 
              - "Authorization"
              - "Cache-Control"
              - "Content-Type"
              - "Accept"
              - "X-Requested-With"
              - "Origin"
            allowCredentials: true
      routes:
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/auth/**, /users/**, /notifications/**, /payments/**, /wallets/**, /api/v1/payment/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
