server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
              - "http://softwarengineer.taild894da.ts.net:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
              - HEAD
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/auth/**, /users/**, /notifications/**, /payments/**, /wallets/**, /api/v1/payment/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: softwarengineer.taild894da.ts.net # Eureka'ya bu isimle kaydol
    prefer-ip-address: false
